import type { NextPage } from 'next'
import Head from 'next/head'
import { SAuthPage, SButton, SCenteredIcon, SCenteredText, SContainer, SFormContainer, SInput, SRow } from '../components/styled'
import { icons } from '../utils/constants'

const Home: NextPage = () => {
  return (
    <SAuthPage>
      <Head>
        <title>Inventory Management System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SContainer>
        <SFormContainer>
          {/* <SRow> */}
          <SCenteredIcon><icons.user /></SCenteredIcon>
          {/* </SRow> */}
          {/* <SCenteredText>Login</SCenteredText> */}
          <SInput placeholder='username' />
          <SInput placeholder='password' type={"password"} />
          <SButton>Login</SButton>
        </SFormContainer>
      </SContainer>
    </SAuthPage>
  )
}

export default Home
